### ISSUE TITLE
Error compiling library in Arduino 1.6.4

### ISSUE THREAD

**Issue by tguidon** [adafruit/HT1632#7]
Error when compiling:

    /Users/tguidon/Documents/Arduino/libraries/HT1632/glcdfont.c:15:23: error: variable 'font' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
     static unsigned char  font[] PROGMEM = {
                       ^
    Error compiling

Sketch compiles fine on Arduino 1.0.5

**Comment by sudiptachatterjee** [comment]
Use this patch: https://github.com/jraymakers/HT1632/commit/e1117180e0339af1dd25781902253019d35e9da8. You need to add the "const" to that file.

**Comment by aklar** [comment]
Great! Thank you! This made my life much easier. Now everything works and it's a lot of fun, hacking the matrix!

**Comment by ericandrewlewis** [comment]
This bug causes a fatal error in the [Adafruit 16x24 LED Matrix tutorial](https://learn.adafruit.com/16x24-led-matrix/testing), and #9 fixes it. Can a project maintainer review the PR? :smile:

**Comment by ericandrewlewis** [comment]
This was probably fixed by 20a3dd5a6d9c8ce34f7608af45831340e184a567
