### PR TITLE
Make library compatible with the latest avr-gcc compiler.

### LINKED ISSUE #7: Error compiling library in Arduino 1.6.4
Error when compiling:

    /Users/tguidon/Documents/Arduino/libraries/HT1632/glcdfont.c:15:23: error: variable 'font' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
     static unsigned char  font[] PROGMEM = {
                       ^
    Error compiling

Sketch compiles fine on Arduino 1.0.5

### PR DESCRIPTION
**Pull request by ericandrewlewis**
Fixes #7.

This is because of changes to the lateset avr-gcc compiler embedded in Arduino 1.6+. [Read more here](https://github.com/arduino/Arduino/wiki/1.6-Frequently-Asked-Questions#q-i-get-an-error-message-that-says-variable-message-must-be-const-in-order-to-be-put-into-read-only-section-by-means-of-__attribute__progmem-char-message-progmem--hello-what-can-i-do).

### CODE REVIEW

**Comment by ericandrewlewis** [comment]
This was split out from @jraymakers work in #6 to isolate the change.

**Comment by ericandrewlewis** [comment]
@tdicola @PaintYourDragon @ladyada can anyone review and merge this? Thank you :smile:

**Comment by bakercp** [comment]
Confirmed that this PR fixes the compiler error on Arduino 1.6.7
